// Blog articles. Kept as structured data (headings / paragraphs / lists) so the
// pages render without a markdown dependency, and so titles/descriptions can
// feed the per-page SEO tags. Newest first.

export const POSTS = [
  {
    slug: 'units-vs-pounds-betting',
    title: 'Units vs pounds: how to size and track your bets',
    description:
      'What a betting unit is, why serious bettors track in units as well as pounds, how to pick a unit size, and how to avoid rewriting your record when your stakes change.',
    date: '2026-10-10',
    read: '5 min read',
    content: [
      { p: 'Spend any time around serious bettors and you’ll hear results quoted in units: “up 14 units this season”, “1u on the favourite”. It can sound like jargon, but it solves a real problem. Here’s what a unit is, why it’s worth tracking, and how to set one up without fooling yourself.' },
      { h2: 'What is a unit?' },
      { p: 'A unit is a fixed amount of money you treat as your standard stake. If your unit is £10, a 1u bet is £10, a 2u bet is £20 and a half-unit bet is £5. Your results are then counted in units rather than pounds: win a £20 bet at 3.0 and you’re up 4u (£40), whatever the pounds happen to be.' },
      { h2: 'Why bother with units?' },
      { ul: [
        'They show how well you’re betting, not how big you’re betting. Winning 5 units is a good month whether your unit is £2 or £50.',
        'They make you comparable. Two people with different budgets can compare records fairly, which is why tipsters report in units.',
        'They stop stake changes hiding the truth. If you raise your stakes after a good run, your pound profit swings more, but your unit record still shows whether your selections are any good.',
        'They encourage consistency. Thinking “1u on this, 0.5u on that” is calmer than picking a random amount each time.',
      ] },
      { h2: 'A quick example' },
      { p: 'Alex stakes £10 units and Sam stakes £50 units. Over a month, both win 6 units. Alex is £60 up and Sam is £300 up. Sam looks five times better, but they’re equally good at picking bets — Sam just stakes more. Units show that. Pounds show what actually landed in your account. You want to see both.' },
      { h2: 'How to choose your unit size' },
      { p: 'There’s no single right answer, but a common rule of thumb is to make a unit a small slice of your betting bankroll, often around 1% to 2%. With a £500 bankroll, that’s £5 to £10. The point is that a losing run shouldn’t be able to hurt: even ten losses in a row costs you only 10 units.' },
      { p: 'Only ever bet money you can afford to lose, and treat your bankroll as separate from your everyday money. A unit is a way of measuring your betting, not a reason to bet more.' },
      { h2: 'Flat or varied stakes?' },
      { p: 'Many bettors use flat staking (1u every time) for simplicity. Others vary between, say, 0.5u and 3u based on how confident they are. Either works for tracking, as long as you record the size of each bet in units. If you vary your stakes, review whether your bigger bets actually do better than your smaller ones — many people find they don’t.' },
      { h2: 'The trap: changing your unit size' },
      { p: 'Suppose your unit is £10 for six months, then you decide a unit should be £25. If your tracker simply re-labels every old bet using the new unit, your history quietly rewrites itself: an old £10 bet suddenly becomes 0.4u, and your past results shrink on paper.' },
      { p: 'The honest way is for each bet to keep the unit size it was placed under. That’s how Betbooks works: change your unit size and your past bets keep the size they had at the time, while new bets use the new one. If you ever want everything re-expressed in the new unit, you can choose that deliberately.' },
      { h2: 'Units and ROI' },
      { p: 'ROI is profit divided by total staked, times 100. If you stake the same amount every time, it comes out the same in pounds or in units. If your stakes vary, the two can differ, which is useful to see: it tells you whether your sizing is helping or hurting.' },
      { h2: 'Putting it into practice' },
      { ul: [
        'Pick a unit size you’re comfortable with.',
        'Log every bet in units as well as pounds.',
        'Review your unit profit and ROI once a week.',
        'If you change your unit size, make sure your tracker keeps past bets as they were.',
      ] },
      { p: 'Betbooks lets you view everything in pounds, in units, or both at once, and keeps each bet’s unit size so your record stays honest. Please gamble responsibly: 18+ only, and visit begambleaware.org if betting stops being fun.' },
    ],
  },
  {
    slug: 'how-to-track-your-bets',
    title: 'How to track your bets (and actually know if you’re winning)',
    description:
      'A simple, honest guide to tracking your bets — what to record, why it matters, and how to finally see whether you’re up or down.',
    date: '2026-09-14',
    read: '5 min read',
    content: [
      { p: 'Most bettors have no idea whether they’re actually winning. They remember the big wins, forget the quiet losses, and “feel” like they’re about even. The only way to know the truth is to track every bet. Here’s how to do it properly — without a messy spreadsheet.' },
      { h2: 'Why tracking changes everything' },
      { p: 'When you write every bet down, three things happen. You stop lying to yourself about your record. You start spotting which sports, bookies and bet types actually make you money. And you naturally bet more carefully, because you know it’s being counted.' },
      { p: 'It’s the single highest-value habit in betting, and it costs you nothing but a few seconds per bet.' },
      { h2: 'What to record for every bet' },
      { p: 'You don’t need much. For each bet, log:' },
      { ul: [
        'The selection and the event (what you backed, and in what game or race).',
        'The stake — how much you put on.',
        'The odds you took.',
        'The bookmaker.',
        'The result — won, lost, void or cashed out — and the actual return.',
      ] },
      { p: 'That’s enough to calculate everything that matters: profit, ROI and win rate. Optional extras like the tipster, sport, or a note help you break results down later.' },
      { h2: 'Track profit in money and units' },
      { p: 'Money profit tells you what’s in your pocket. Units tell you how well you’re actually betting, independent of stake size. A unit is simply a fixed slice of your bankroll (say £10). Winning 5 units is a good month whether your unit is £2 or £200 — so serious bettors judge themselves in units.' },
      { p: 'The best trackers show you both at once, so you can see you’re “+£120 / +12u” at a glance.' },
      { h2: 'Review it regularly' },
      { p: 'Tracking is only useful if you look back. Once a week, check your net profit and ROI, and ask: which sport is carrying me? Which bookie or bet type is leaking money? Cut what loses, lean into what wins.' },
      { h2: 'Make it effortless' },
      { p: 'The reason people quit tracking is friction — spreadsheets are slow and ugly on a phone. Betbooks is built to log a bet in seconds and show your profit, ROI, win rate and unit performance automatically, so the habit actually sticks.' },
    ],
  },
  {
    slug: 'betting-roi-explained',
    title: 'Betting ROI explained: the one number that matters',
    description:
      'What ROI means in betting, how to calculate it, and why it’s a better measure of your betting than raw profit or win rate.',
    date: '2026-09-13',
    read: '4 min read',
    content: [
      { p: 'Ask a sharp bettor how they’re doing and they won’t tell you their win rate — they’ll tell you their ROI. Here’s what it means, how to work it out, and why it’s the number to obsess over.' },
      { h2: 'What is ROI?' },
      { p: 'ROI (return on investment) is your profit as a percentage of everything you’ve staked. It answers: “for every £1 I put through, how much do I make back?”' },
      { p: 'The formula is simple:' },
      { ul: ['ROI = (total profit ÷ total staked) × 100'] },
      { p: 'If you’ve staked £1,000 across the season and you’re £70 up, your ROI is 7%. That means you make 7p of profit for every £1 you risk.' },
      { h2: 'Why ROI beats win rate' },
      { p: 'Win rate — the percentage of bets you win — is misleading on its own. You can win 70% of your bets and still lose money if you’re backing short-priced favourites, and you can win 35% and be hugely profitable backing big prices. Win rate ignores odds. ROI doesn’t.' },
      { h2: 'Why ROI beats raw profit' },
      { p: 'Raw profit doesn’t tell you how efficient you are. £200 profit from £500 staked (40% ROI) is elite. £200 profit from £20,000 staked (1% ROI) is barely beating the vig and one bad run from turning negative. ROI puts your profit in context.' },
      { h2: 'What’s a good ROI?' },
      { p: 'Be realistic. Professional sports bettors often operate on 3–5% ROI over huge volume — that’s genuinely excellent. Anything consistently above 0% over hundreds of bets means you’re beating the bookmaker, which most people never do. Short-term ROI swings wildly; judge it over a big sample.' },
      { h2: 'Track it automatically' },
      { p: 'You can’t improve what you don’t measure. Betbooks calculates your ROI for you as you log bets, and lets you break it down by sport, bookmaker and bet type — so you can see exactly where your edge is, and where it isn’t.' },
    ],
  },
  {
    slug: 'bankroll-management-and-staking',
    title: 'Bankroll management and staking: how to stay in the game',
    description:
      'Units, stake sizing and staking plans explained — the discipline that separates bettors who last from those who go bust.',
    date: '2026-09-12',
    read: '6 min read',
    content: [
      { p: 'You can pick winners and still go broke. The bettors who last aren’t just good at finding value — they’re disciplined about how much they stake. This is bankroll management, and it’s the least glamorous, most important skill in betting.' },
      { h2: 'Your bankroll is your business capital' },
      { p: 'Your bankroll is the money you’ve set aside purely for betting — money you can afford to lose, kept separate from rent and bills. Treat it like a business’s working capital: protect it, and never top it up on tilt.' },
      { h2: 'Bet in units, not gut feelings' },
      { p: 'A unit is a fixed percentage of your bankroll — commonly 1–2%. If your bankroll is £500 and a unit is 1%, that’s £5 per unit. Instead of staking random amounts, you stake in units: a standard bet might be 1 unit, a strong one 2 units.' },
      { p: 'Why it works: units keep your stakes proportional to your bankroll, so a losing run can’t wipe you out, and a winning run scales up naturally.' },
      { h2: 'Common staking plans' },
      { ul: [
        'Flat staking — the same stake (e.g. 1 unit) on every bet. Boring, robust, and hard to beat for most people.',
        'Percentage staking — always stake a fixed % of your current bankroll, so stakes shrink when you’re down and grow when you’re up.',
        'Confidence-based — 1 unit for standard bets, 2 for strong ones. Only works if you’re honest about confidence.',
      ] },
      { p: 'For almost everyone, flat or percentage staking is the right answer. Avoid chasing losses by doubling up — that’s how bankrolls die.' },
      { h2: 'The rules that keep you alive' },
      { ul: [
        'Never stake more than a small % of your bankroll on one bet (1–2% is sensible).',
        'Never chase losses with bigger stakes to “get it back”.',
        'Set your unit size in advance and stick to it.',
        'Withdraw profit periodically so it’s real, not just a number.',
      ] },
      { h2: 'Measure yourself in units' },
      { p: 'Once you stake in units, judge your results in units too. “+8 units this month” is a clean measure of how well you bet, whatever your stake size. Betbooks tracks your unit profit alongside your money profit, and lets you set your unit size once so every bet is measured consistently.' },
      { p: 'Bet within your means, and if it ever stops being fun, stop. Free, confidential help is always available at begambleaware.org.' },
    ],
  },
];

export const getPost = (slug) => POSTS.find((p) => p.slug === slug);
